id_card 21.jpg done
Apnasite/icard-assignments pull request #2
Opened 2024-07-24 10:58 UTC by Bhosle07

2024-07-31 16:19 UTC, jaiminkumar1810 commented on I card/Bhosle_Mahesh_21.jpg/id_card/index.html
> +            <div class="id-number2">id no: 123456</div>
There are no id-number2 class in sample change it according to sample code

2024-07-31 16:23 UTC, jaiminkumar1810 commented on I card/Bhosle_Mahesh_21.jpg/id_card/index.html
> +                <div class="dates">
Remove this div class name dates, if you have any issue to set content of ID Back Card write separate CSS for each class eg. id-blood-group/id-dob/id-issue-date/id-expiry-date

2024-07-31 16:25 UTC, jaiminkumar1810 commented on I card/Bhosle_Mahesh_21.jpg/id_card/index.html
> +             <div class="my-name"><span>BHOSLE</span><H1>MAHI</H1></div>
The class name should be **user-name** instead of my-name

2024-07-31 16:26 UTC, jaiminkumar1810 requested changes
Check the comment and update your code ASAP

2024-09-20 13:24 UTC, Adarshovhal reviewed
All Requirement are Done like, In css file mm and pt unit are used.
All classes in the previous.html file.
Background classes in the index.html file.
Code was good in structure.

2024-09-21 08:54 UTC, merged